MODEL:
  DEVICE: 'cpu'
  NAME: 'cdnet'
  # NAME: 'cnet'
  PRETRAIN_PATH: ''
  IMAGENET_CKPT: '/home/share/solicucu/data/ReID/FasterReID/inference/classification/imagenet60_cdnet_top2.pth'
  USE_BNNECK: False 
  PARALLEL: False
  WIDTH_MULT: 1.
  STAGES: [2, 2, 2]
  PLANES: [64, 256, 384, 512]
  GENOTYPE: "cdnet_sample_top2_best_genotype.json"
  NECK_TYPE: "fblneck"
  ADAPTION_FUSION: True
  FC_DIMS: [512]

DATA:
  DATASET: 'market1501'
  # DATASET: 'dukemtmc'
  # DATASET: 'msmt17'
  DATASET_DIR: "/home/share/solicucu/data/"
  IMAGE_SIZE: [256,128]
  HF_PROB: 0.5
  RE_PROB: 0.5
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  PADDING: 10

DATALOADER:
  NUM_WORKERS: 4
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4

SOLVER:
  MAX_EPOCHS: 350
  # MAX_EPOCHS: 240 # for msmt
  BATCH_SIZE: 64

  BASE_LR: 6.5e-2
  # BASE_LR: 0.045 # for msmt
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  # LR_SCHEDULER_NAME: "WarmupCosAnnLR"
  LR_MIN: 0.0001
  WARMUP_ITERS: 0
  WARMUP_FACTOR: 1.0
  MILESTONES: [150, 225, 300]
  LR_LIST: [6.5e-2, 6.5e-3, 6.5e-4, 6.5e-5]
  # LR_LIST: [4.5e-2, 4.5e-3, 4.5e-4, 4.5e-5] # for msmt


  OPTIMIZER_NAME: "SGD"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005

  LOSS_NAME: "softmax_triplet"
  TRI_MARGIN: 0.3

  GRAD_CLIP: 0.

OUTPUT:
  # DIRS: "/home/share/solicucu/data/ReID/FasterReID/market1501/cnet/"
  # DIRS: "/home/share/solicucu/data/ReID/FasterReID/dukemtmc/cnet/"
  # DIRS: "/home/share/solicucu/data/ReID/FasterReID/msmt17/cdnet/"
  # DIRS: "/home/share/solicucu/data/ReID/FasterReID/dukemtmc/cdnet/"
  DIRS: "/home/share/solicucu/data/ReID/FasterReID/market1501/cdnet/"
  CKPT_DIRS: "checkpoints/cdnet_top2_fblneck_pretrained/"
  LOG_NAME: 'log_cdnet_top2_fblneck_pretrained.txt'
 
  LOG_PERIOD: 10
  CKPT_PERIOD: 20
  EVAL_PERIOD: 20

TRICKS:
  LABEL_SMOOTH: False
  DROPOUT: 0.2

TEST:
  IMGS_PER_BATCH: 256
  FEAT_NORM: 'yes'
  BEST_CKPT: "best_ckpt.pth"
