MODEL:
  DEVICE: 'cpu'
  NAME: 'cdnet'
  # NAME: 'cnet'
  PRETRAIN_PATH: ''
  IMAGENET_CKPT: ''
  USE_BNNECK: False
  PARALLEL: True
  WIDTH_MULT: 1.0
  STAGES: [2, 2, 2]
  PLANES: [64, 256, 384, 512]
  GENOTYPE: "cdnet_sample_top2_best_genotype.json"
  NECK_TYPE: "fblneck"
  ADAPTION_FUSION: True
  FC_DIMS: [512]

DATA:
  DATASET: 'imagenet'
  DATASET_DIR: "/home/share/solicucu/data/imagenet/train_val/"
  IMAGE_SIZE: [224, 224]
  HF_PROB: 0.5
  RE_PROB: 0.5
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  PADDING: 10

DATALOADER:
  NUM_WORKERS: 8
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4

SOLVER:
  MAX_EPOCHS: 240
  BATCH_SIZE: 128

  BASE_LR: 0.1
  LR_DECAY_PERIOD: 1
  LR_DECAY_FACTOR: 0.97
  LR_SCHEDULER_NAME: "StepLR"
  LR_MIN: 0.0001
  WARMUP_ITERS: 0
  WARMUP_FACTOR: 1.0
  MILESTONES: [150, 225, 300]
  LR_LIST: [6.5e-2, 6.5e-3, 6.5e-4, 6.5e-5]


  OPTIMIZER_NAME: "SGD"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 3.e-5 
  LOSS_NAME: "softmax"
  TRI_MARGIN: 0.3

  GRAD_CLIP: 0.

OUTPUT:
  DIRS: "/home/share/solicucu/data/ReID/FasterReID/imagenet/cdnet/"
  # DIRS: "/home/share/solicucu/data/ReID/FasterReID/imagenet/cnet/"
  CKPT_DIRS: "checkpoints/cdnet_top2_fblneck/"
  LOG_NAME: 'log_cdnet_top2_fblneck.txt'
  LOG_PERIOD: 100
  CKPT_PERIOD: 5
  EVAL_PERIOD: 10

TRICKS:
  LABEL_SMOOTH: False
  DROPOUT: 0.2

TEST:
  IMGS_PER_BATCH: 128
  FEAT_NORM: 'yes'
  BEST_CKPT: "best_ckpt.pth"
