MODEL:
  DEVICE: 'cpu'
  NAME: 'mobilenetv2'
  PRETRAIN_PATH: ''
  IMAGENET_CKPT: ''
  USE_BNNECK: False
  PARALLEL: False
  WIDTH_MULT: 1.
  NECK_TYPE: "blneck"
  FC_DIMS: [512]

DATA:
  DATASET: 'market1501'
  DATASET_DIR: "/home/share/solicucu/data/"
  IMAGE_SIZE: [256,128]
  HF_PROB: 0.5
  RE_PROB: 0.5
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  PADDING: 10

DATALOADER:
  NUM_WORKERS: 4
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4

SOLVER:
  MAX_EPOCHS: 350
  BATCH_SIZE: 64

  # BASE_LR: 3.5e-4
  BASE_LR: 0.025
  LR_DECAY_PERIOD: 100
  LR_DECAY_FACTOR: 0.1
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  # LR_SCHEDULER_NAME: "WarmupCosAnnLR"
  LR_MIN: 0.0001
  WARMUP_ITERS: 0
  WARMUP_FACTOR: 1.0
  MILESTONES: [150, 225, 300]
  LR_LIST: [6.5e-2, 6.5e-3, 6.5e-4, 6.5e-5]

  OPTIMIZER_NAME: "SGD"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005

  LOSS_NAME: "softmax_triplet"
  TRI_MARGIN: 0.3

  GRAD_CLIP: 0.

OUTPUT:
  DIRS: "/home/share/solicucu/data/ReID/ReIDModels/mobilenetv2/market1501/"
  CKPT_DIRS: "checkpoints/mobilenetv2_blneck/"
  LOG_NAME: 'log_mobilenetv2_blneck.txt'
  LOG_PERIOD: 10
  CKPT_PERIOD: 20
  EVAL_PERIOD: 20

TRICKS:
  LABEL_SMOOTH: False
  DROPOUT: 0.0

TEST:
  IMGS_PER_BATCH: 128
  FEAT_NORM: 'yes'
  BEST_CKPT: "best_ckpt.pth"
